# Generated by Django 4.1.5 on 2026-02-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('agreement1', models.BooleanField()),
                ('agreement2', models.BooleanField()),
                ('agreement3', models.BooleanField()),
                ('agreement4', models.BooleanField()),
                ('ball_pro', models.IntegerField(default=0)),
                ('ball_rus', models.IntegerField(default=0)),
                ('ball_mat', models.IntegerField(default=0)),
                ('ball_ind', models.IntegerField(default=0)),
                ('ball_sum', models.IntegerField(default=0)),
                ('priority1', models.IntegerField(default=0)),
                ('priority2', models.IntegerField(default=0)),
                ('priority3', models.IntegerField(default=0)),
                ('priority4', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
