# Generated by Django 4.1.5 on 2026-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ID',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='agreement1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='agreement2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='agreement3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='agreement4',
            field=models.BooleanField(default=False),
        ),
    ]
