# Generated by Django 4.1.5 on 2026-02-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1dayago',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agreement1', models.BooleanField(default=False)),
                ('agreement2', models.BooleanField(default=False)),
                ('agreement3', models.BooleanField(default=False)),
                ('agreement4', models.BooleanField(default=False)),
                ('ball_pro', models.IntegerField(default=0)),
                ('ball_rus', models.IntegerField(default=0)),
                ('ball_mat', models.IntegerField(default=0)),
                ('ball_ind', models.IntegerField(default=0)),
                ('ball_sum', models.IntegerField(default=0)),
                ('priority1', models.IntegerField(default=0)),
                ('priority2', models.IntegerField(default=0)),
                ('priority3', models.IntegerField(default=0)),
                ('priority4', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student2dayago',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agreement1', models.BooleanField(default=False)),
                ('agreement2', models.BooleanField(default=False)),
                ('agreement3', models.BooleanField(default=False)),
                ('agreement4', models.BooleanField(default=False)),
                ('ball_pro', models.IntegerField(default=0)),
                ('ball_rus', models.IntegerField(default=0)),
                ('ball_mat', models.IntegerField(default=0)),
                ('ball_ind', models.IntegerField(default=0)),
                ('ball_sum', models.IntegerField(default=0)),
                ('priority1', models.IntegerField(default=0)),
                ('priority2', models.IntegerField(default=0)),
                ('priority3', models.IntegerField(default=0)),
                ('priority4', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student3dayago',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agreement1', models.BooleanField(default=False)),
                ('agreement2', models.BooleanField(default=False)),
                ('agreement3', models.BooleanField(default=False)),
                ('agreement4', models.BooleanField(default=False)),
                ('ball_pro', models.IntegerField(default=0)),
                ('ball_rus', models.IntegerField(default=0)),
                ('ball_mat', models.IntegerField(default=0)),
                ('ball_ind', models.IntegerField(default=0)),
                ('ball_sum', models.IntegerField(default=0)),
                ('priority1', models.IntegerField(default=0)),
                ('priority2', models.IntegerField(default=0)),
                ('priority3', models.IntegerField(default=0)),
                ('priority4', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
