# Generated by Django 4.1.5 on 2026-02-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student1dayago_student2dayago_student3dayago'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynBal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField()),
                ('date', models.DateField()),
                ('passing_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('direction', 'date')},
            },
        ),
    ]
